---
driver:
  name: vagrant

driver_config:
  customize:
    memory: 512

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-15.04
- name: ubuntu-14.04
- name: ubuntu-12.04
- name: debian-8.1
- name: debian-7.8
- name: debian-6.0.10
- name: centos-7.1
- name: centos-6.6
- name: centos-5.11

suites:
  - name: default
    run_list:
      - recipe[iptables-ng]
    attributes:
      iptables-ng:
        rules:
          filter:
            INPUT:
              ssh:
                rule: '--protocol tcp --dport 22 --match state --state NEW --jump ACCEPT'
              ipv4_only:
                rule: '--protocol tcp --source 1.2.3.4 --dport 123 --jump ACCEPT'
                ip_version: 4
            OUTPUT:
                testrule:
                  rule: '--protocol icmp --jump ACCEPT'
            FORWARD:
              default: 'DROP [0:0]'
          nat:
            POSTROUTING:
              nat_test:
                rule: '--protocol tcp -j ACCEPT'
          mangle:
            FORWARD:
              default: 'DROP [0:0]'
