---
driver:
  name: vagrant

driver_config:
  customize:
    memory: 512

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.10
- name: ubuntu-14.04
- name: ubuntu-12.04
- name: debian-8.1
- name: debian-7.8
- name: debian-6.0.10
- name: centos-7.1
- name: centos-6.6
- name: centos-5.11

suites:
  - name: default
    run_list:
      recipe[iptables-ng]
    attributes:
      iptables-ng:
        rules:
          filter:
            FORWARD:
              default: 'DROP [0:0]'
