---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-13.04
  driver_config:
    box: opscode-ubuntu-13.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-13.04_provisionerless.box

- name: ubuntu-12.10
  driver_config:
    box: opscode-ubuntu-12.10
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.10_provisionerless.box

- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box

- name: debian-7.1.0
  driver_config:
    box: opscode-debian-7.1.0
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_debian-7.1.0_provisionerless.box

- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box


suites:
- name: lwrp_chain_create_default
  run_list:
  - recipe[minitest-handler]
  - recipe[iptables_ng_test::lwrp_chain_create_default]
- name: lwrp_chain_create_custom
  run_list:
  - recipe[minitest-handler]
  - recipe[iptables_ng_test::lwrp_chain_create_custom]
- name: lwrp_chain_create_if_missing
  run_list:
  - recipe[minitest-handler]
  - recipe[iptables_ng_test::lwrp_chain_create_if_missing]
- name: lwrp_chain_create_empty
  run_list:
  - recipe[minitest-handler]
  - recipe[iptables_ng_test::lwrp_chain_create_empty]

- name: lwrp_rule_create_default
  run_list:
  - recipe[minitest-handler]
  - recipe[iptables_ng_test::lwrp_rule_create_default]
- name: lwrp_rule_create_custom
  run_list:
  - recipe[minitest-handler]
  - recipe[iptables_ng_test::lwrp_rule_create_custom]
- name: lwrp_rule_create_custom_chain
  run_list:
  - recipe[minitest-handler]
  - recipe[iptables_ng_test::lwrp_rule_create_custom_chain]
- name: lwrp_rule_create_invalid_custom_chain
  run_list:
  - recipe[minitest-handler]
  - recipe[iptables_ng_test::lwrp_rule_create_invalid_custom_chain]
- name: lwrp_rule_create_toolong_custom_chain
  run_list:
  - recipe[minitest-handler]
  - recipe[iptables_ng_test::lwrp_rule_create_toolong_custom_chain]
- name: lwrp_rule_create_if_missing
  run_list:
  - recipe[minitest-handler]
  - recipe[iptables_ng_test::lwrp_rule_create_if_missing]
- name: lwrp_rule_delete
  run_list:
  - recipe[minitest-handler]
  - recipe[iptables_ng_test::lwrp_rule_delete]
- name: lwrp_rule_check_order
  run_list:
  - recipe[minitest-handler]
  - recipe[iptables_ng_test::lwrp_rule_check_order]

- name: recipe_default
  run_list:
  - recipe[minitest-handler]
  - recipe[iptables_ng_test::recipe_default]
  attributes:
    iptables-ng:
      rules:
        filter:
          INPUT:
            ssh:
              rule: '--protocol tcp --dport 22 --match state --state NEW --jump ACCEPT'
            ipv4_only:
              rule: '--protocol tcp --source 1.2.3.4 --dport 123 --jump ACCEPT'
              ip_version: 4
          OUTPUT:
              testrule:
                rule: '--protocol icmp --jump ACCEPT'
          FORWARD:
            default: 'DROP [0:0]'
        nat:
          POSTROUTING:
            nat_test:
              rule: '--protocol tcp -j ACCEPT'
        mangle:
          FORWARD:
            default: 'DROP [0:0]'

- name: recipe_install
  run_list:
  - recipe[minitest-handler]
  - recipe[iptables_ng_test::recipe_install]

