LineLength:
  Max: 200

HashSyntax:
  EnforcedStyle: ruby19

CaseIndentation:
  IndentWhenRelativeTo: end

MethodLength:
  Max: 50

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

SpaceBeforeFirstArg:
  Enabled: false

AbcSize:
  Enabled: false

TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

EmptyLinesAroundBlockBody:
  Enabled: false
