LineLength:
  Max: 200

HashSyntax:
  EnforcedStyle: ruby19

CaseIndentation:
  IndentWhenRelativeTo: end

MethodLength:
  Max: 50

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

Style/SpaceBeforeFirstArg:
  Enabled: false

AbcSize:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

EmptyLinesAroundBlockBody:
  Enabled: false

ConditionalAssignment:
  Enabled: false
