name: Chef

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
        # NOTE: Commented out (older) versions do not work on Github Actions with this cookbook
          # - 'centos-7'
          - 'centos-8'
          - 'debian-10'
          - 'debian-11'
          # - 'ubuntu-1604'
          # - 'ubuntu-1804'
          # - 'ubuntu-2004'
          - 'ubuntu-2204'
        suite:
          - 'lwrp-chain-create-default'
          - 'lwrp-chain-create-custom'
          - 'lwrp-chain-create-if-missing'
          - 'lwrp-chain-create-empty'
          - 'lwrp-rule-create-default'
          - 'lwrp-rule-create-custom'
          - 'lwrp-rule-create-custom-chain'
          - 'lwrp-rule-create-if-missing'
          - 'lwrp-rule-delete'
          - 'lwrp-rule-check-order'
          - 'default'
          - 'install'
          - 'attribute-enabled-tables'
      fail-fast: false
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Install Chef
      uses: actionshub/chef-install@main
    - name: Linting
      run: cookstyle -f simple || (echo "Run 'cookstyle -a' to correct cookstyle errors." && exit 1)
    - name: test-kitchen
      uses: actionshub/test-kitchen@main
      with:
        suite: ${{ matrix.suite }}
        os: ${{ matrix.os }}
      env:
        CHEF_LICENSE: accept-no-persist
        KITCHEN_LOCAL_YAML: kitchen.dokken.yml
